- name: get status of /opt/{{ application_server_archive }}
  stat:
    path: /opt/{{ application_server_archive }}
  register: download_file

- name: download app server
  get_url:
    url: '{{ application_server_download_url }}'
    dest: /opt
    checksum: '{{ application_server_archive_checksum }}'
  # testing the checksum is very slow or does it work at all?
  # this additional check works better as a new file is a new file-name
  when: not download_file.stat.exists
  become: true

- name: unpack app server
  unarchive:
    remote_src: yes
    src: /opt/{{ application_server_archive }}
    dest: '/opt'
    owner: '{{ application_server_user }}'
    group: '{{ application_server_group }}'
    creates: '{{ application_server_start_script }}'
  become: true

- name: link app server home
  file:
    state: link
    src: '/opt/{{ application_server_archive_expanded }}'
    name: '{{ application_server_home }}'
    owner: '{{ application_server_user }}'
    group: '{{ application_server_group }}'
  become: true
