---
# tasks file for jee-ansible-role
- include: install-java.yaml
- include: create-roles.yaml
- include: download-app-server.yaml
- include: wildfly-systemd.yaml
  when: ansible_service_mgr == 'systemd'
