---
scenario:
  name: vagrant
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
- name: jee-molecule-ubuntu-18.04
  box: ubuntu/bionic64 # 18.04
  memory: 512
  cpus: 1
- name: jee-molecule-centos-7
  box: centos/7
  memory: 512
  cpus: 1

provisioner:
  name: ansible
  playbooks:
    converge: ../converge.yaml

verifier:
  name: testinfra
  directory: ../tests/
  options:
    v: 1 # show which tests where executed in test output
