---
scenario:
  name: vagrant
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: vagrant-ubuntu
    box: ubuntu/bionic64
    memory: 512
    cpus: 1
lint:
  name: yamllint

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../playbook.yaml

verifier:
  name: testinfra
  directory: ../tests/
  lint:
    name: flake8
  options:
    v: 1 # show which tests where executed in test output
